### ISSUE TITLE
Typo in howto_for_non-developers.md

### ISSUE THREAD

**Issue by DeeperWaters** [ericyd/gdrive-transfer#2]
Step 1 should be `git clone https://github.com/ericyd/gdrive-transfer.git `
Also, as a tinkerer-but-not-developer, would love to know what prompt I'm supposed to be typing the commands into. On a Windows box, with lots of Google, I kludged through it anyway :)

**Comment by ericyd** [comment]
I'm actually shocked that you got it to work! As far as I know you're the first positive test case.

I've made a few updates based on your notes so I'm going to close this out but feel free to make other suggestions.
