### ISSUE TITLE
remove this extension

### ISSUE THREAD

**Issue by wmclaxton** [ericyd/gdrive-transfer#5]
I don't see a Chrome Extension for Transfer Ownership.  How do I remove it from my system?

**Comment by ericyd** [comment]
If you don't see it installed then it probably isn't installed. I actually never wrote it as a proper extension, it is just a web app. The chrome store is weird so it makes it look like an extension but in all likelihood you don't need to do anything.

If you would like to remove permissions, please see this help article, section "Remove site or app access" 

https://support.google.com/accounts/answer/3466521?hl=en

**Comment by wmclaxton** [comment]
Thank you, this was helpful.  I did find 'Transfer Ownership' in the list of third-party apps having permissions, and removed it.
