### ISSUE TITLE
Ownership Locked on Everything in Originating Google Drive

### ISSUE THREAD

**Issue by jpoole70** [ericyd/gdrive-transfer#7]
I used this app as recommended and it transferred ownership of my folder and Google Files just fine.  However, I am now unable to manually change the ownership of any file, including PDFs, in the same originating Google Drive.

Now whenever I try to change ownership on a non-Google File type, I get the following error, "You can't yet change the owner of this item.  (We're working on it.)"  

Any suggestions?

**Comment by ericyd** [comment]
That's simply a limitation of Google drive, it has nothing to do with this app
